### ISSUE TITLE
Docs sprint Checklist

### ISSUE THREAD

**Issue by carimura** [fnproject/fn#371]
- [ ] Tutorial series links (Mike updating)
- [ ] UI docs (Mike updating / see comments below)
- [ ] K8s docs (Derek updating)
- [ ] Swarm docs (update or delete)
- [ ] ..
- [ ] ..
- [ ] ..

**Comment by carimura** [comment]
@michael-w-williams shall we close this one?

**Comment by michael-w-williams** [comment]
You bet.
